version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.9
    working_directory: /home/circleci/.go_workspace/src/github.com/r3labs/akira
    steps:
      - checkout
      - run: make dev-deps
      - run: make test
